# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9647ec847a36553ebdecc116ae37f13f36ed22ead56ee027cc5e68522f3413ebafa98e73cec059d01a31417a69940c50477fe1ad9b59efe6118b5ae458addef

test:
  secret_key_base: 86078bec3d9ae50a5d7ce482ffa99324fc9fa51de5288903fade9d8cc77443ac7817ba0a3a6af98821e58aae276a0e3f578229b17cfb8a27e6b67665cebc92cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
